config/routes.rb
Rails.application.routes.draw do

   root 'users#index'
   resources :users do
     resources :dogs
   end

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController


  def new
    @dog = Dog.new
    @user = User.find(params[:user_id])
  end

    # Actions needed to create a dog?
    #
    def create
      @dog = Dog.new(dog_params)
      @dog.user_id = params[:user_id]

      if @dog.save
      redirect_to users_path, notice: 'You created a dog'
      else
        render users_path(@user)
      end
    end

private
  def dog_params
    params.require(:dog).permit(:name, :breed, :age, :user_id)

end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
      @dogs = @user.dogs
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/_form.html.erb
<%= form_for [@user, @dog] do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :breed %>
<%= f.text_field :breed %>

<%= f.label :age %>
<%= f.number_field :age %>

<%= f.submit %>
<% end %>

app/views/dogs/new.html.erb
form to create a dog goes here!
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BelongsTo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<table>
  <tr>
    <th> First Name </th>
    <th> Last Name </th>
    <th> Email </th>
    <th></th>
    <th></th>
  </tr>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.first_name, user %> </td>
        <td><%= user.last_name %> </td>
        <td><%= user.email %> </td>
        <td><%= link_to "Create Dog", new_user_dog_path(user) %> </td>
      </tr>
      <% end %>
      </tbody>
</table>

app/views/users/show.html.erb
List all of the this users dogs in the table!


<table>
  <tr>
    <th> Dog Name </th>
    <th> Dog Breed </th>
    <th> Age </th>
  </tr>

  <tbody>
        <tr><% @user.dogs.each do |dog| %>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.age %></td>
      </tr>
            <% end %>
      </tbody>
</table>